# docker-compose.yml
version: '3.8'
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 6432:5432

  api:
    image: node
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - database.env # configure postgres
    ports:
      - 8000:8000
    volumes:
      - .:/api
      - ./error.log:/usr/src/app/error.log
    depends_on:  
      - "database"
  
  app:
    container_name: app
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
    ports:
      - 3000:3000
    depends_on:  
      - api
    stdin_open: true
    

volumes:
  database-data: # named volumes can be managed easier using docker-compose
  api:
  app:
